export default cartConstants = {
    CART_FETCH_SUCCESS: 'CART_FETCH_SUCCESS',
    CART_FETCH_FAILURE: 'CART_FETCH_FAILURE',
    CART_ADD_PRODUCT_SUCCESS: 'CART_ADD_PRODUCT_SUCCESS',
    CART_ADD_PRODUCT_FAILURE: 'CART_ADD_PRODUCT_FAILURE'
};