export default employeeConstants = {
    EMPLOYEES_FETCH_START: 'EMPLOYEES_FETCH_START',
    EMPLOYEES_FETCH_SUCCESS: 'EMPLOYEES_FETCH_SUCCESS',
    EMPLOYEES_FETCH_FAILURE: 'EMPLOYEES_FETCH_FAILURE',
};