export default cartConstants = {
	PRODUCT_LIST_FETCH_SUCCESS: 'PRODUCT_LIST_FETCH_SUCCESS',
	PRODUCT_LIST_FETCH_FAILURE: 'PRODUCT_LIST_FETCH_FAILURE',
    PRODUCT_DETAILS_FETCH_SUCCESS: 'PRODUCT_DETAILS_FETCH_SUCCESS',
	PRODUCT_DETAILS_FETCH_FAILURE: 'PRODUCT_DETAILS_FETCH_FAILURE',
	PRODUCT_ADDED_TO_CART: 'PRODUCT_ADDED_TO_CART'
};
